name: Deploy Backend 
run-name: ${{ github.actor }} triggered backend pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Backend
      url: ${{ vars.URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd 3-tier-prod-cicd
            git add .
            git stash
            git pull origin main
            docker compose up -d --no-deps --build backend