name: Deploy Backend
run-name: ${{ github.actor }} triggered backend pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Backend
      url: ${{ vars.URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          script: |
            # Your deployment script goes here
            cd 3-tier-prod-cicd-main
            git add .
            git stash
            git pull origin main
            docker compose up -d --no-deps --build backend

      