name: Deploy Frontend 
run-name: ${{ github.actor }} triggered frontend pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Frontend
      url: ${{ vars.URL }}  # Variable for URL

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Use SSH Action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}             # The hostname or IP of your server
          username: ${{ secrets.USERNAME }}      # The SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # The private key stored in GitHub Secrets
          script: |
            cd /  # Navigate to the root directory
            if [ ! -d "3-tier-prod-cicd" ]; then
              echo "Directory 3-tier-prod-cicd does not exist."
              exit 1
            fi

            cd 3-tier-prod-cicd
            if [ ! -d ".git" ]; then
              echo "Not a git repository."
              exit 1
            fi
            
            git add .
            git stash
            git pull origin main
            docker compose up -d --no-deps --build frontend
